export const BIBLE_BOOKS = [
{"chapters": 50, "id": "gn", "name": "Gênesis"},
{"chapters": 40, "id": "ex", "name": "Êxodo"},
{"chapters": 27, "id": "lv", "name": "Levítico"},
{"chapters": 36, "id": "nm", "name": "Números"},
{"chapters": 34, "id": "dt", "name": "Deuteronômio"},
{"chapters": 24, "id": "js", "name": "Josué"},
{"chapters": 21, "id": "jz", "name": "Juízes"},
{"chapters": 4, "id": "rt", "name": "Rute"},
{"chapters": 31, "id": "1sm", "name": "1º Samuel"},
{"chapters": 24, "id": "2sm", "name": "2º Samuel"},
{"chapters": 22, "id": "1rs", "name": "1º Reis"},
{"chapters": 25, "id": "2rs", "name": "2º Reis"},
{"chapters": 29, "id": "1cr", "name": "1º Crônicas"},
{"chapters": 36, "id": "2cr", "name": "2º Crônicas"},
{"chapters": 10, "id": "ed", "name": "Esdras"},
{"chapters": 13, "id": "ne", "name": "Neemias"},
{"chapters": 10, "id": "et", "name": "Ester"},
{"chapters": 42, "id": "job", "name": "Jó"},
{"chapters": 150, "id": "sl", "name": "Salmos"},
{"chapters": 31, "id": "pv", "name": "Provérbios"},
{"chapters": 12, "id": "ec", "name": "Eclesiastes"},
{"chapters": 8, "id": "ct", "name": "Cânticos"},
{"chapters": 66, "id": "is", "name": "Isaías"},
{"chapters": 52, "id": "jr", "name": "Jeremias"},
{"chapters": 5, "id": "lm", "name": "Lamentações de Jeremias"},
{"chapters": 48, "id": "ez", "name": "Ezequiel"},
{"chapters": 12, "id": "dn", "name": "Daniel"},
{"chapters": 14, "id": "os", "name": "Oséias"},
{"chapters": 3, "id": "jl", "name": "Joel"},
{"chapters": 9, "id": "am", "name": "Amós"},
{"chapters": 1, "id": "ob", "name": "Obadias"},
{"chapters": 4, "id": "jn", "name": "Jonas"},
{"chapters": 7, "id": "mq", "name": "Miquéias"},
{"chapters": 3, "id": "na", "name": "Naum"},
{"chapters": 3, "id": "hc", "name": "Habacuque"},
{"chapters": 3, "id": "sf", "name": "Sofonias"},
{"chapters": 2, "id": "ag", "name": "Ageu"},
{"chapters": 14, "id": "zc", "name": "Zacarias"},
{"chapters": 4, "id": "ml", "name": "Malaquias"},
{"chapters": 28, "id": "mt", "name": "Mateus"},
{"chapters": 16, "id": "mc", "name": "Marcos"},
{"chapters": 24, "id": "lc", "name": "Lucas"},
{"chapters": 21, "id": "jo", "name": "João"},
{"chapters": 28, "id": "at", "name": "Atos"},
{"chapters": 16, "id": "rm", "name": "Romanos"},
{"chapters": 16, "id": "1co", "name": "1ª Coríntios"},
{"chapters": 13, "id": "2co", "name": "2ª Coríntios"},
{"chapters": 6, "id": "gl", "name": "Gálatas"},
{"chapters": 6, "id": "ef", "name": "Efésios"},
{"chapters": 4, "id": "fp", "name": "Filipenses"},
{"chapters": 4, "id": "cl", "name": "Colossenses"},
{"chapters": 5, "id": "1ts", "name": "1ª Tessalonicenses"},
{"chapters": 3, "id": "2ts", "name": "2ª Tessalonicenses"},
{"chapters": 6, "id": "1tm", "name": "1ª Timóteo"},
{"chapters": 4, "id": "2tm", "name": "2ª Timóteo"},
{"chapters": 3, "id": "tt", "name": "Tito"},
{"chapters": 1, "id": "fm", "name": "Filemom"},
{"chapters": 13, "id": "hb", "name": "Hebreus"},
{"chapters": 5, "id": "tg", "name": "Tiago"},
{"chapters": 5, "id": "1pe", "name": "1ª Pedro"},
{"chapters": 3, "id": "2pe", "name": "2ª Pedro"},
{"chapters": 5, "id": "1jo", "name": "1ª João"},
{"chapters": 1, "id": "2jo", "name": "2ª João"},
{"chapters": 1, "id": "3jo", "name": "3ª João"},
{"chapters": 1, "id": "jd", "name": "Judas"},
{"chapters": 22, "id": "ap", "name": "Apocalipse"},
]